
const BAD_REQUEST_CODE = 400
const UN_AUTHORIZED_CODE = 401
const DUPLICATE_CODE = 409
const SERVER_ERROR_CODE = 500
const SUCCESS_REQUEST = 200

export {
  BAD_REQUEST_CODE,
  UN_AUTHORIZED_CODE,
  DUPLICATE_CODE,
  SERVER_ERROR_CODE,
  SUCCESS_REQUEST
}
